import {
  pgTable,
  text,
  timestamp,
  integer,
  uuid,
  index,
  boolean,
  numeric,
  date,
  serial,
  unique,
} from "drizzle-orm/pg-core";

export const nbaVenues = pgTable("nba_venues", {
  venueId: integer("venue_id").primaryKey(),
  name: text("name").notNull(),
  city: text("city"),
  state: text("state"),
  country: text("country").default("USA"),
  capacity: integer("capacity"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const nbaTeamProfiles = pgTable("nba_team_profiles", {
  teamId: integer("team_id").primaryKey(),
  teamUuid: uuid("team_uuid"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  city: text("city"),
  conference: text("conference"),
  division: text("division"),
  primaryColor: text("primary_color"),
  secondaryColor: text("secondary_color"),
  headCoach: text("head_coach"),
  venueId: integer("venue_id").references(() => nbaVenues.venueId),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("nba_team_profiles_team_uuid_idx").on(table.teamUuid),
]);

export const nbaPlayers = pgTable("nba_players", {
  playerId: integer("player_id").primaryKey(),
  teamId: integer("team_id").references(() => nbaTeamProfiles.teamId),
  firstName: text("first_name"),
  lastName: text("last_name"),
  fullName: text("full_name").notNull(),
  position: text("position"),
  jerseyNumber: integer("jersey_number"),
  heightInches: integer("height_inches"),
  weightLbs: integer("weight_lbs"),
  birthDate: date("birth_date"),
  college: text("college"),
  experience: integer("experience"),
  status: text("status"),
  injuryStatus: text("injury_status"),
  injuryBodyPart: text("injury_body_part"),
  injuryNote: text("injury_note"),
  headshotUrl: text("headshot_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("nba_players_team_idx").on(table.teamId),
]);

export const nbaGames = pgTable("nba_games", {
  gameId: integer("game_id").primaryKey(),
  eventId: uuid("event_id"),
  seasonYear: integer("season_year").notNull(),
  seasonType: text("season_type").notNull(),
  gameDate: date("game_date").notNull(),
  gameDatetime: timestamp("game_datetime", { withTimezone: true }),
  homeTeamId: integer("home_team_id").references(() => nbaTeamProfiles.teamId),
  awayTeamId: integer("away_team_id").references(() => nbaTeamProfiles.teamId),
  venueId: integer("venue_id").references(() => nbaVenues.venueId),
  homeScore: integer("home_score"),
  awayScore: integer("away_score"),
  status: text("status"),
  currentQuarter: integer("current_quarter"),
  timeRemaining: text("time_remaining"),
  attendance: integer("attendance"),
  isOvertime: boolean("is_overtime").default(false),
  overtimePeriods: integer("overtime_periods").default(0),
  neutralVenue: boolean("neutral_venue").default(false),
  channel: text("channel"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("nba_games_event_idx").on(table.eventId),
  index("nba_games_date_idx").on(table.gameDate),
]);

export const nbaPlayerGameStats = pgTable("nba_player_game_stats", {
  id: serial("id").primaryKey(),
  gameId: integer("game_id").notNull().references(() => nbaGames.gameId),
  playerId: integer("player_id").notNull().references(() => nbaPlayers.playerId),
  teamId: integer("team_id").notNull().references(() => nbaTeamProfiles.teamId),
  opponentTeamId: integer("opponent_team_id").references(() => nbaTeamProfiles.teamId),
  seasonYear: integer("season_year").notNull(),
  gameDate: date("game_date").notNull(),
  homeOrAway: text("home_or_away"),
  isStarter: boolean("is_starter"),
  didNotPlay: boolean("did_not_play").default(false),
  minutes: numeric("minutes", { precision: 5, scale: 2 }),
  points: integer("points"),
  rebounds: integer("rebounds"),
  assists: integer("assists"),
  steals: integer("steals"),
  blocks: integer("blocks"),
  turnovers: integer("turnovers"),
  fieldGoalsMade: integer("field_goals_made"),
  fieldGoalsAttempted: integer("field_goals_attempted"),
  threePointersMade: integer("three_pointers_made"),
  threePointersAttempted: integer("three_pointers_attempted"),
  freeThrowsMade: integer("free_throws_made"),
  freeThrowsAttempted: integer("free_throws_attempted"),
  plusMinus: integer("plus_minus"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("nba_player_game_stats_game_player_unique").on(table.gameId, table.playerId),
  index("nba_player_game_stats_player_idx").on(table.playerId),
]);

export const nbaTeamGameStats = pgTable("nba_team_game_stats", {
  id: serial("id").primaryKey(),
  gameId: integer("game_id").notNull().references(() => nbaGames.gameId),
  teamId: integer("team_id").notNull().references(() => nbaTeamProfiles.teamId),
  opponentTeamId: integer("opponent_team_id").references(() => nbaTeamProfiles.teamId),
  seasonYear: integer("season_year").notNull(),
  gameDate: date("game_date").notNull(),
  homeOrAway: text("home_or_away"),
  won: boolean("won"),
  points: integer("points"),
  opponentPoints: integer("opponent_points"),
  rebounds: integer("rebounds"),
  assists: integer("assists"),
  fieldGoalsPct: numeric("field_goals_pct", { precision: 5, scale: 4 }),
  threePointersPct: numeric("three_pointers_pct", { precision: 5, scale: 4 }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("nba_team_game_stats_game_team_unique").on(table.gameId, table.teamId),
  index("nba_team_game_stats_team_idx").on(table.teamId),
]);

export const nbaTeamSeasonStats = pgTable("nba_team_season_stats", {
  id: serial("id").primaryKey(),
  teamId: integer("team_id").notNull().references(() => nbaTeamProfiles.teamId),
  seasonYear: integer("season_year").notNull(),
  seasonType: text("season_type").default("REG"),
  gamesPlayed: integer("games_played"),
  wins: integer("wins"),
  losses: integer("losses"),
  pointsPerGame: numeric("points_per_game", { precision: 6, scale: 2 }),
  opponentPointsPerGame: numeric("opponent_points_per_game", { precision: 6, scale: 2 }),
  pointDifferential: numeric("point_differential", { precision: 6, scale: 2 }),
  reboundsPerGame: numeric("rebounds_per_game", { precision: 5, scale: 2 }),
  assistsPerGame: numeric("assists_per_game", { precision: 5, scale: 2 }),
  homeWins: integer("home_wins"),
  homeLosses: integer("home_losses"),
  awayWins: integer("away_wins"),
  awayLosses: integer("away_losses"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("nba_team_season_stats_team_season_unique").on(table.teamId, table.seasonYear, table.seasonType),
]);

export const nbaStandings = pgTable("nba_standings", {
  id: serial("id").primaryKey(),
  teamId: integer("team_id").notNull().references(() => nbaTeamProfiles.teamId),
  seasonYear: integer("season_year").notNull(),
  seasonType: text("season_type").default("REG"),
  wins: integer("wins"),
  losses: integer("losses"),
  winPct: numeric("win_pct", { precision: 5, scale: 4 }),
  gamesBack: numeric("games_back", { precision: 5, scale: 1 }),
  conferenceRank: integer("conference_rank"),
  divisionRank: integer("division_rank"),
  leagueRank: integer("league_rank"),
  homeWins: integer("home_wins"),
  homeLosses: integer("home_losses"),
  awayWins: integer("away_wins"),
  awayLosses: integer("away_losses"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("nba_standings_team_season_unique").on(table.teamId, table.seasonYear, table.seasonType),
]);
